package theme

var themes = []Theme{
	{ID: "rgb-linux", Name: "100% LINUX!!!!!!", Distro: "RGB Linux", Logo: "tux", Primary: "#ff2bd6", Secondary: "#32e6ff", Accent: "#b6ff35", Tagline: "100% LINUX!!!!!! zero doubts detected", Desktop: "KDE Plasma ∞", Joke: true, Rainbow: true},
	{ID: "seriously-linux", Name: "Seriously Linux", Distro: "Seriously Linux", Logo: "tux", Primary: "#f7c948", Secondary: "#f4f4f5", Accent: "#ff6b6b", Tagline: "seriously. this is Linux. stop checking.", Desktop: "KDE Plasma 6 (seriously)", Joke: true},
	{ID: "trust-me-bro", Name: "Trust Me Bro", Distro: "TrustMe Linux", Logo: "tux", Primary: "#8b5cf6", Secondary: "#e9d5ff", Accent: "#22d3ee", Tagline: "Trust me, it's Linux.", Desktop: "KDE Plasma 6", Joke: true},
	{ID: "arch-btw", Name: "Arch BTW", Distro: "Arch Linux", Logo: "arch", Primary: "#1793d1", Secondary: "#e6f6ff", Accent: "#60a5fa", Tagline: "I use Arch on a Mac, btw.", Desktop: "KDE Plasma 6", Joke: true},
	{ID: "kde-delusion", Name: "KDE Delusion", Distro: "Plasma Linux", Logo: "kde", Primary: "#1d99f3", Secondary: "#eff8ff", Accent: "#6ee7b7", Tagline: "Retina is just HiDPI Wayland with branding.", Desktop: "KDE Plasma 6.6.6", Joke: true},
	{ID: "sudo-believe", Name: "Sudo Believe", Distro: "BeliefOS", Logo: "sudo", Primary: "#fb7185", Secondary: "#fff1f2", Accent: "#facc15", Tagline: "sudo believe --force", Desktop: "KDE Plasma 6", Joke: true},
	{ID: "kernel-of-truth", Name: "Kernel of Truth", Distro: "Definitely Linux", Logo: "linux", Primary: "#a3e635", Secondary: "#f7fee7", Accent: "#22c55e", Tagline: "Darwin is a Linux kernel if you don't look it up.", Desktop: "KDE Plasma 6", Joke: true},
	{ID: "macos-who", Name: "macOS Who?", Distro: "Not macOS", Logo: "apple_glitch", Primary: "#f472b6", Secondary: "#fdf2f8", Accent: "#c084fc", Tagline: "macOS was not found on this device.", Desktop: "KDE Plasma 6", Joke: true},
	{ID: "penguin-certified", Name: "Penguin Certified", Distro: "Tux Certified Linux", Logo: "tux", Primary: "#fbbf24", Secondary: "#f8fafc", Accent: "#38bdf8", Tagline: "Certified by one extremely credible penguin.", Desktop: "KDE Plasma 6", Joke: true},
	{ID: "retina-wayland", Name: "Retina Wayland", Distro: "Wayland Pro Max", Logo: "wayland", Primary: "#ef4444", Secondary: "#fef2f2", Accent: "#60a5fa", Tagline: "One hundred percent native Wayland. Probably.", Desktop: "KDE Plasma 6", Joke: true},
	{ID: "arch", Name: "Arch Classic", Distro: "Arch Linux", Logo: "arch", Primary: "#1793d1", Secondary: "#e5e7eb", Accent: "#38bdf8", Tagline: "A clean Arch-inspired profile.", Desktop: "KDE Plasma 6"},
	{ID: "ubuntu", Name: "Ubuntu", Distro: "Ubuntu", Logo: "ubuntu", Primary: "#e95420", Secondary: "#f5f5f4", Accent: "#f97316", Tagline: "Humanity, now available on Apple silicon.", Desktop: "GNOME 48"},
	{ID: "debian", Name: "Debian", Distro: "Debian GNU/Linux", Logo: "debian", Primary: "#d70a53", Secondary: "#fce7f3", Accent: "#fb7185", Tagline: "The universal operating system, allegedly.", Desktop: "KDE Plasma 6"},
	{ID: "fedora", Name: "Fedora", Distro: "Fedora Linux", Logo: "fedora", Primary: "#51a2da", Secondary: "#eff6ff", Accent: "#2563eb", Tagline: "Leading edge, suspicious hardware.", Desktop: "GNOME 48"},
	{ID: "nixos", Name: "NixOS", Distro: "NixOS", Logo: "nixos", Primary: "#7ebae4", Secondary: "#e0f2fe", Accent: "#5277c3", Tagline: "Reproducibly pretending to be Linux.", Desktop: "KDE Plasma 6"},
	{ID: "alpine", Name: "Alpine", Distro: "Alpine Linux", Logo: "alpine", Primary: "#0d597f", Secondary: "#e0f2fe", Accent: "#38bdf8", Tagline: "Small, simple, secure, and on a Mac.", Desktop: "KDE Plasma 6"},
	{ID: "manjaro", Name: "Manjaro", Distro: "Manjaro Linux", Logo: "manjaro", Primary: "#35bf5c", Secondary: "#ecfdf5", Accent: "#10b981", Tagline: "Enjoy the simplicity.", Desktop: "KDE Plasma 6"},
	{ID: "endeavour", Name: "EndeavourOS", Distro: "EndeavourOS", Logo: "endeavour", Primary: "#7f3fbf", Secondary: "#f3e8ff", Accent: "#ef4444", Tagline: "A terminal-centric journey through denial.", Desktop: "KDE Plasma 6"},
	{ID: "opensuse", Name: "openSUSE", Distro: "openSUSE Tumbleweed", Logo: "opensuse", Primary: "#73ba25", Secondary: "#f7fee7", Accent: "#22c55e", Tagline: "Have a lot of fun.", Desktop: "KDE Plasma 6"},
	{ID: "gentoo", Name: "Gentoo", Distro: "Gentoo Linux", Logo: "gentoo", Primary: "#54487a", Secondary: "#ede9fe", Accent: "#8b5cf6", Tagline: "Compiled from source while you were sleeping.", Desktop: "KDE Plasma 6"},
	{ID: "kali", Name: "Kali", Distro: "Kali Linux", Logo: "kali", Primary: "#557c94", Secondary: "#e2e8f0", Accent: "#38bdf8", Tagline: "Please use responsibly, even as a joke.", Desktop: "KDE Plasma 6"},
	{ID: "mint", Name: "Linux Mint", Distro: "Linux Mint", Logo: "mint", Primary: "#87cf3e", Secondary: "#f7fee7", Accent: "#4ade80", Tagline: "From freedom came elegance.", Desktop: "Cinnamon 6"},
	{ID: "popos", Name: "Pop!_OS", Distro: "Pop!_OS", Logo: "popos", Primary: "#48b9c7", Secondary: "#ecfeff", Accent: "#f9d72f", Tagline: "Pop open a terminal and believe.", Desktop: "COSMIC"},
	{ID: "elementary", Name: "elementary OS", Distro: "elementary OS", Logo: "elementary", Primary: "#64baff", Secondary: "#f8fafc", Accent: "#a3a3a3", Tagline: "Thoughtful, capable, and entirely fictional.", Desktop: "Pantheon"},
	{ID: "void", Name: "Void", Distro: "Void Linux", Logo: "void", Primary: "#478061", Secondary: "#ecfdf5", Accent: "#84cc16", Tagline: "Enter the void. It looks like macOS.", Desktop: "KDE Plasma 6"},
	{ID: "slackware", Name: "Slackware", Distro: "Slackware Linux", Logo: "slackware", Primary: "#1a4c8b", Secondary: "#dbeafe", Accent: "#60a5fa", Tagline: "Keep it simple. Keep it credible.", Desktop: "KDE Plasma 6"},
	{ID: "rocky", Name: "Rocky", Distro: "Rocky Linux", Logo: "rocky", Primary: "#10b981", Secondary: "#ecfdf5", Accent: "#34d399", Tagline: "Enterprise-grade make-believe.", Desktop: "GNOME 48"},
	{ID: "alma", Name: "AlmaLinux", Distro: "AlmaLinux", Logo: "alma", Primary: "#ffb71b", Secondary: "#fff7ed", Accent: "#00a6a6", Tagline: "For the community, by the imagination.", Desktop: "GNOME 48"},
	{ID: "centos", Name: "CentOS Stream", Distro: "CentOS Stream", Logo: "centos", Primary: "#932279", Secondary: "#faf5ff", Accent: "#efa724", Tagline: "Streaming directly from an alternate reality.", Desktop: "GNOME 48"},
	{ID: "garuda", Name: "Garuda", Distro: "Garuda Linux", Logo: "garuda", Primary: "#dd3cc7", Secondary: "#fdf4ff", Accent: "#38bdf8", Tagline: "Performance tuned for opening Finder.", Desktop: "KDE Plasma 6"},
	{ID: "cachyos", Name: "CachyOS", Distro: "CachyOS", Logo: "cachyos", Primary: "#00d1b2", Secondary: "#ecfeff", Accent: "#22d3ee", Tagline: "Optimized beyond the limits of plausibility.", Desktop: "KDE Plasma 6"},
	{ID: "neon", Name: "KDE neon", Distro: "KDE neon", Logo: "kde", Primary: "#1d99f3", Secondary: "#f0f9ff", Accent: "#22d3ee", Tagline: "The latest and greatest from KDE.", Desktop: "KDE Plasma 6"},
}
